# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'reactNativeTestApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativeTestApp
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNAnalytics', :path => '../node_modules/@segment/analytics-react-native'


  # target 'reactNativeTestApp-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'reactNativeTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactNativeTestApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativeTestApp-tvOS

  target 'reactNativeTestApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
